---
# tasks file for update_os

- name: Update OS using yum but firefox
  yum:
    name: "*"
    state: latest
    update_cache: true
    update_only: true
    exclude: firefox*
  notify:
    - Reboot system after update
